using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: ExportFont("icomoon.ttf", Alias = "icomoon")]
[assembly: ExportFont("MaterialIcons.ttf", Alias = "material")]
[assembly: ExportFont("Montserrat-Black.ttf", Alias = "Black")]
[assembly: ExportFont("Montserrat-BlackItalic.ttf", Alias = "BlackItalic")]
[assembly: ExportFont("Montserrat-Bold.ttf", Alias = "Bold")]
[assembly: ExportFont("Montserrat-BoldItalic.ttf", Alias = "material")]
[assembly: ExportFont("Montserrat-ExtraBold.ttf", Alias = "BoldItalic")]
[assembly: ExportFont("Montserrat-ExtraBoldItalic.ttf", Alias = "ExtraBold")]
[assembly: ExportFont("Montserrat-ExtraLight.ttf", Alias = "ExtraBoldItalic")]
[assembly: ExportFont("Montserrat-ExtraLightItalic.ttf", Alias = "ExtraLight")]
[assembly: ExportFont("Montserrat-ExtraLightItalic.ttf", Alias = "ExtraLightItalic")]
[assembly: ExportFont("Montserrat-Italic.ttf", Alias = "Italic")]
[assembly: ExportFont("Montserrat-Light.ttf", Alias = "Light")]
[assembly: ExportFont("Montserrat-LightItalic.ttf", Alias = "LightItalic")]
[assembly: ExportFont("Montserrat-Medium.ttf", Alias = "Medium")]
[assembly: ExportFont("Montserrat-MediumItalic.ttf", Alias = "MediumItalic")]
[assembly: ExportFont("Montserrat-Regular.ttf", Alias = "Regular")]
[assembly: ExportFont("Montserrat-SemiBold.ttf", Alias = "SemiBold")]
[assembly: ExportFont("Montserrat-SemiBoldItalic.ttf", Alias = "SemiBoldItalic")]
[assembly: ExportFont("Montserrat-Thin.ttf", Alias = "Thin")]
[assembly: ExportFont("Montserrat-ThinItalic.ttf", Alias = "ThinItalic")]
